# Configuração de Desenvolvimento para Extrato API
spring:
  # Configuração do DataSource para Desenvolvimento
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:financas_db}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppassword}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Configuração JPA para Desenvolvimento
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 10
        format_sql: true

  # Configuração do RabbitMQ para Desenvolvimento
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 1

  # Configuração de CORS para Desenvolvimento
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:4000"
        - "http://127.0.0.1:3000"
        - "http://127.0.0.1:4000"
        - "http://localhost:8080"
        - "http://127.0.0.1:8080"

# Configuração de observabilidade para Desenvolvimento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Configuração de logging para Desenvolvimento
logging:
  level:
    "[br.com.financas.extrato_api]": DEBUG
    "[org.springframework.web]": DEBUG
    "[com.zaxxer.hikari]": DEBUG
    "[org.springframework.transaction]": DEBUG
    "[org.springframework.orm.jpa]": DEBUG
    "[org.springframework.jdbc]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# Configuração de parser para Desenvolvimento
parser:
  general:
    parallel-processing: false
    batch-size: 100
    validation:
      strict-file-type: false
      max-file-size-mb: 10

