# Configuração de Produção para Extrato API
spring:
  profiles:
    active: prod
  
  # Configuração do DataSource para Produção
  datasource:
    url: jdbc:mysql://${DB_HOST:financas-db.cluster-xyz.us-east-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:financas_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Configuração JPA para Produção
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 50

  # Configuração do RabbitMQ para Produção
  rabbitmq:
    host: ${RABBITMQ_HOST:financas-rabbitmq.elb.amazonaws.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

  # Configuração de CORS para Produção
  web:
    cors:
      allowed-origins: 
        - "https://financas.example.com"
        - "https://app.financas.example.com"
      allowed-methods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Configuração de observabilidade para Produção
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 0.1

# Configuração de logging para Produção
logging:
  level:
    "[br.com.financas.extrato_api]": INFO
    "[org.springframework.web]": WARN
    "[com.zaxxer.hikari]": WARN
    "[org.springframework.transaction]": WARN
    "[org.springframework.orm.jpa]": WARN
    "[org.springframework.jdbc]": WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# Configuração de parser para Produção
parser:
  general:
    parallel-processing: true
    batch-size: 2000
    validation:
      strict-file-type: true
      max-file-size-mb: 100


# Configuração de segurança para Produção
server:
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
  port: 8443
