# Configuração de Banco de Dados para Desenvolvimento
spring:
  # Configuração do DataSource com HikariCP
  datasource:
    url: jdbc:mysql://mysql:3306/financas_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: appuser
    password: apppassword
    
    # ✅ Configurações específicas do HikariCP
    hikari:
      # Pool de conexões
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
      # Configurações de transação
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
      
      # Configurações de performance
      leak-detection-threshold: 60000
      register-mbeans: true
      
      # Configurações específicas do MySQL
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  # Configurações JPA com transações
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
    # Configurações de transação
    properties:
      hibernate:
        transaction:
          jta:
            platform: enable
        # Configurações de transação
        connection:
          "[provider_disables_autocommit]": true
        jdbc:
          "[batch_size]": 20
          "[batch_versioned_data]": true
        "[order_inserts]": true
        "[order_updates]": true
        # Configurações de cache
        cache:
          "[use_second_level_cache]": false
          "[use_query_cache]": false