# Configuração do Event Broker (RabbitMQ) para Desenvolvimento
spring:
  # Configuração do RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
        concurrency: 3
        max-concurrency: 10
        prefetch: 1