# Configurações de Cache por Ambiente
# Este arquivo contém as configurações específicas de cache para cada ambiente

# Desenvolvimento
---
spring:
  profiles: dev
cache:
  type: simple
  cache-names:
    - "extratos"
    - "bancos"
    - "configurations"
  caffeine:
    spec: "maximumSize=100,expireAfterWrite=5m"
  redis:
    enabled: false
    host: localhost
    port: 6379
    password: ""
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# Homologação
---
spring:
  profiles: hml
cache:
  type: redis
  cache-names:
    - "extratos"
    - "bancos"
    - "configurations"
  caffeine:
    spec: "maximumSize=1000,expireAfterWrite=10m"
  redis:
    enabled: true
    host: ${REDIS_HOST:hml-redis.amazonaws.com}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 4

# Produção
---
spring:
  profiles: prod
cache:
  type: redis
  cache-names:
    - "extratos"
    - "bancos"
    - "configurations"
  caffeine:
    spec: "maximumSize=10000,expireAfterWrite=30m"
  redis:
    enabled: true
    host: ${REDIS_HOST:prod-redis.amazonaws.com}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 32
        max-idle: 32
        min-idle: 8

# AWS Free Tier (para testes)
---
spring:
  profiles: aws-free
cache:
  type: simple
  cache-names:
    - "extratos"
  caffeine:
    spec: "maximumSize=50,expireAfterWrite=5m"
  redis:
    enabled: false
    host: localhost
    port: 6379
    password: ""
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 4
        max-idle: 4
        min-idle: 0