# Configurações de Compressão por Ambiente
# Este arquivo contém as configurações específicas de compressão para cada ambiente

# Desenvolvimento
---
spring:
  profiles: dev
server:
  compression:
    enabled: false

# Homologação
---
spring:
  profiles: hml
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

# Produção
---
spring:
  profiles: prod
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

# AWS Free Tier (para testes)
---
spring:
  profiles: aws-free
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 2048
