# Configurações de CORS por Ambiente
# Este arquivo contém as configurações específicas de CORS para cada ambiente

# Desenvolvimento
---
spring:
  profiles: dev
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:4000"
        - "http://127.0.0.1:3000"
        - "http://127.0.0.1:4000"
        - "http://localhost:8080"
        - "http://127.0.0.1:8080"
      allowed-methods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        - "PATCH"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Homologação
---
spring:
  profiles: hml
  web:
    cors:
      allowed-origins: 
        - "https://hml-financas.example.com"
        - "https://hml-app.financas.example.com"
        - "http://localhost:3000"
      allowed-methods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Produção
---
spring:
  profiles: prod
  web:
    cors:
      allowed-origins: 
        - "https://financas.example.com"
        - "https://app.financas.example.com"
      allowed-methods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# AWS Free Tier (para testes)
---
spring:
  profiles: aws-free
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
      allowed-methods: 
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
