# Configurações de Monitoramento por Ambiente
# Este arquivo contém as configurações específicas de monitoramento para cada ambiente

# Desenvolvimento
---
spring:
  profiles: dev
monitoring:
  enabled: true
  health-check:
    enabled: true
    interval: 30s
    timeout: 5s
  metrics:
    enabled: true
    collection-interval: 10s
  alerts:
    enabled: false
  dashboards:
    enabled: true
    refresh-interval: 30s

# Homologação
---
spring:
  profiles: hml
monitoring:
  enabled: true
  health-check:
    enabled: true
    interval: 60s
    timeout: 10s
  metrics:
    enabled: true
    collection-interval: 30s
  alerts:
    enabled: true
    channels:
      - email
      - slack
  dashboards:
    enabled: true
    refresh-interval: 60s

# Produção
---
spring:
  profiles: prod
monitoring:
  enabled: true
  health-check:
    enabled: true
    interval: 30s
    timeout: 5s
  metrics:
    enabled: true
    collection-interval: 60s
  alerts:
    enabled: true
    channels:
      - email
      - slack
      - pagerduty
  dashboards:
    enabled: true
    refresh-interval: 30s

# AWS Free Tier (para testes)
---
spring:
  profiles: aws-free
monitoring:
  enabled: true
  health-check:
    enabled: true
    interval: 120s
    timeout: 10s
  metrics:
    enabled: true
    collection-interval: 120s
  alerts:
    enabled: false
  dashboards:
    enabled: true
    refresh-interval: 120s
