# Configurações de Swagger por Ambiente
# Este arquivo contém as configurações específicas de Swagger para cada ambiente

# Desenvolvimento
---
spring:
  profiles: dev
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
  override-with-generic-response: false
  use-hal-as-default-json-media-type: false

# Homologação
---
spring:
  profiles: hml
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
  override-with-generic-response: false
  use-hal-as-default-json-media-type: false

# Produção
---
spring:
  profiles: prod
springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: false
    filter: false
    displayRequestDuration: false
    displayOperationId: false
    showExtensions: false
    showCommonExtensions: false
  override-with-generic-response: false
  use-hal-as-default-json-media-type: false

# AWS Free Tier (para testes)
---
spring:
  profiles: aws-free
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
  override-with-generic-response: false
  use-hal-as-default-json-media-type: false
