# Configuração da Fatura API - Ambiente de Desenvolvimento
# Este arquivo é servido pelo Config Server

spring:
  application:
    name: fatura-api
  
  # Configuração do DataSource com HikariCP
  datasource:
    url: jdbc:mysql://mysql:3306/financas_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: appuser
    password: apppassword
    
    # ✅ Configurações específicas do HikariCP
    hikari:
      # Pool de conexões
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
      # Configurações de transação
      auto-commit: false
      connection-test-query: SELECT 1
      validation-timeout: 5000
      
      # Configurações de performance
      leak-detection-threshold: 60000
      register-mbeans: true
      
      # Configurações específicas do MySQL
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  
  # Configurações JPA com transações
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
    # Configurações de transação
    open-in-view: false
    
    # Configurações de performance
    properties:
      hibernate:
        # Configurações de batch
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        
        # Configurações de cache
        cache:
          use_second_level_cache: false
          use_query_cache: false
        
        # Configurações de conexão
        connection:
          provider_disables_autocommit: true
        
        # Configurações de logging
        format_sql: false
        use_sql_comments: false
  
  # Configuração do RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 60000
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Configuração de logging
logging:
  level:
    "[br.com.financas.fatura_api]": INFO
    "[org.springframework.amqp]": WARN
    "[org.springframework.orm.jpa]": WARN

# Configuração de Bancos Suportados
bancos:
  suporte:
    names:
      - "banco-do-brasil"
      - "itau"

# Configuração dos Parsers de Fatura
parser:
  auto-discovery:
    base-package: "br.com.financas.fatura_api.parser"
    enabled: true
    scan-depth: 2
  config:
    banco-do-brasil:
      name: "Banco do Brasil"
      file-patterns:
        - ".*bb.*\\.pdf$"
        - ".*banco.*brasil.*\\.pdf$"
      supported-extensions: [".pdf"]
      pdf:
        date-format: "dd/MM/yyyy"
        date-regex: "^\\d{2}/\\d{2}/\\d{4}$"
        value-regex: "^[+-]?\\d{1,3}([.,]\\d{3})*([.,]\\d{1,2})?$|^[+-]?\\d+([.,]\\d{1,2})?$"
        transaction-regex: "(\\d{2}/\\d{2}/\\d{4})\\s+(.+?)\\s+([+-]?\\d{1,3}(?:\\.\\d{3})*(?:,\\d{2})?)(?:\\s+([+-]?\\d{1,3}(?:\\.\\d{3})*(?:,\\d{2})?))?\\s*$"
        header-regex: ".*agência:.*|.*conta:.*|.*saldo em conta.*"
        pais: "BR"
        idioma: "pt"
        text-extraction:
          sort-by-position: true
          encoding: "UTF-8"
    itau:
      name: "Itaú"
      file-patterns:
        - ".*itau.*\\.pdf$"
        - ".*\\.pdf$"
      supported-extensions: [".pdf"]
      pdf:
        date-format: "dd/MM/yyyy"
        date-regex: "^\\d{2}/\\d{2}/\\d{4}$"
        value-regex: "^[+-]?\\d{1,3}([.,]\\d{3})*([.,]\\d{1,2})?$|^[+-]?\\d+([.,]\\d{1,2})?$"
        transaction-regex: "(\\d{2}/\\d{2}/\\d{4})\\s+(.+?)\\s+([+-]?\\d{1,3}(?:\\.\\d{3})*(?:,\\d{2})?)(?:\\s+([+-]?\\d{1,3}(?:\\.\\d{3})*(?:,\\d{2})?))?\\s*$"
        header-regex: ".*agência:.*|.*conta:.*|.*saldo em conta.*"
        pais: "BR"
        idioma: "pt"
        text-extraction:
          sort-by-position: true
          encoding: "UTF-8"
  general:
    parallel-processing: true
    batch-size: 1000
    validation:
      strict-file-type: true
      max-file-size-mb: 50

# Configuração de observabilidade
observability:
  metrics:
    enabled: true
  tracing:
    enabled: true
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://zipkin:9411}
