# Configurações Compartilhadas de Observabilidade
# Estas configurações são aplicadas a todos os microserviços para monitoramento

# Configuração de observabilidade
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,tracing
  endpoint:
    health:
      show-details: always
    metrics:
      access: read-only
    prometheus:
      access: read-only
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99
      slo:
        "[http.server.requests]": 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

# Configuração de logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  level:
    "[org.springframework.web]": INFO
    "[com.zaxxer.hikari]": INFO
    "[org.springframework.transaction]": INFO
    "[org.springframework.orm.jpa]": INFO
    "[org.springframework.jdbc]": INFO

# Configurações específicas por ambiente
---
spring:
  profiles: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[com.zaxxer.hikari]": DEBUG
    "[org.springframework.transaction]": DEBUG
    "[org.springframework.orm.jpa]": DEBUG
    "[org.springframework.jdbc]": DEBUG

---
spring:
  profiles: prod
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    "[org.springframework.web]": WARN
    "[com.zaxxer.hikari]": WARN
    "[org.springframework.transaction]": WARN
    "[org.springframework.orm.jpa]": WARN
    "[org.springframework.jdbc]": WARN

---
spring:
  profiles: hml
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.5

logging:
  level:
    "[org.springframework.web]": INFO
    "[com.zaxxer.hikari]": INFO
    "[org.springframework.transaction]": INFO
    "[org.springframework.orm.jpa]": INFO
    "[org.springframework.jdbc]": INFO
